# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('counter', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('poked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedpokes', to='belt.User')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokerpokes', to='belt.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='pokes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pokes',
        ),
    ]
