# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0007_auto_20180325_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='total',
        ),
        migrations.AddField(
            model_name='poke',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
